[package]
name = "trigger"
version = "0.1.0"
authors = ["Steven Pease <peasteven@gmail.com>"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc-4.7"

[dependencies]
ctrlc = "3.1"
failure = "0.1"
log = "0.4"
pyo3 = "0.2"
rppal = "0.2"
